### ISSUE TITLE
Redirect all text output to stderr and add flag to suppress non-errors

### ISSUE THREAD

**Issue by marcospb19** [ouch-org/ouch#114]
_Originally posted by @marcospb19 in https://github.com/ouch-org/ouch/issues/110#issuecomment-946958436_

# Steps

1. Use `eprint` instead of `print`.
2. add `-q/--quiet` flag.

# Reasoning:

1. Will make it possible for us to use STDOUT as the output of compression and decompression.
2. With everything in the `stderr`, the user loses the ability of redirecting only the errors to a log file, by adding the `--quiet` flag, we provide a decent way of logging it.

---

Example of redirection:

```sh
ouch decompress -q file.xz 2> ouch.log
```

**Comment by marcospb19** [comment]
From https://github.com/ouch-org/ouch/issues/110#issuecomment-946961949:

in addition to a quiet flag, we can also use [tracing](https://lib.rs/crates/tracing) with [EnvFilter](https://docs.rs/tracing-subscriber/*/tracing_subscriber/struct.EnvFilter.html) from [tracing-subscriber](https://lib.rs/crates/tracing-subscriber)

**Comment by marcospb19** [comment]
I would love to see `tracing` being used in `ouch` for this, even tho I have no prior experience with it.

**Comment by marcospb19** [comment]
The first point kills it, no `tracing` then :thinking:.

**Comment by SpyrosRoum** [comment]
Here is another option. 
Two simple declarative macros:
```rust
macro_rules! stdout_println {
    ($($arg : tt) *) => {
        if atty::is(atty::Stream::Stdout) {
            println!($($arg)*);
        }
    };
}

macro_rules! stdout_print {
    ($($arg : tt) *) => {
        if atty::is(atty::Stream::Stdout) {
            print!($($arg)*);
        }
    };
}
```

So we can use the usual `println` for when we want to definetly output something, `eprintln` for errors, and the macros for logs and other info.

Thoughts?

**Comment by figsoda** [comment]
I still prefer only compressing and decompressing to stdout and printing everything else to stderr

**Comment by figsoda** [comment]
Could you elaborate on what could be confusing/annoying about printing all the logs and messages to stderr?

**Comment by SpyrosRoum** [comment]
.. This is what I'm trying to say.

Running the first command produces this if successful:
`[INFO] Successfully compressed 'foo.xz'.`
and maybe it will produce this too
`Do you want to overwrite 'foo.xz'? [Y/n]`

If we print all that to stderr then using `2>` will not show either of them,

**Comment by marcospb19** [comment]
This however impacts #77, because using a simple BufWriter<Stderr> would be simpler than having to worry about the synchronization between STDOUT and STDERR.

**Comment by AntonHermann** [comment]
> I think tracing might be a bit overkill and some normal logs would suffice. Also two points:
> 1. If we use a logging/tracing lib we won't be able to redirect its output to stderr

I haven't used [tracing](https://crates.io/crates/tracing) yet, I only used the older [log](https://crates.io/crates/log) crate and with that it is definitely possible to write all `log` output to stderr (in fact thats the default for many logging frontends (see e.g. [simplelog](https://crates.io/crates/simplelog) or [flexi_logger](https://crates.io/crates/flexi_logger))

---

My usual initial setup for CLI apps includes the following:
- `log` + either `simplelog` or `flex_logger`
- optional CLI argument `--logfile <PATH>`
- CLI flag `--verbose` / `-v` with `#[clap(parse(from_occurences))]` which is used to filter the `log` output that goes to stderr (e.g. no `-v` = warnings and errors, 1 x `-v` = info, warn, err, 2 x `-v` = debug, warn, error, ... (`log` has 5 logging macros: `trace!`, `debug!`, `info!`, `warn!`, `error!` with increasing severity)

This way the user can control what is logged via env variables and if he wants to write all log output to a file, he can provide the optional `--logfile` argument. In either case, depending on `-v`-usage, errors, warnings and maybe more are written to stderr (maybe a `--quiet` flag could suppress this completely)

# Advantages
- stdout can be freely used, no logging / status messages there
- The user has very much control where he wants his logs, how detailled they should be etc.
- Using the lower priority `debug!` or `trace!` macros could help while debugging (we could dump intermediate state, ... to `debug` or `trace`, being only visible if run via `RUST_LOG=trace ouch`

# Disadvantages
- Some boilerplate for logging, 1-3 extra command line arguments (although very understandable ones in my opinion)
  The boilerplate isn't that much actually, ca. 13 lines for setting up `flexi_logger` for example

# Unresolved questions
How do we handle our question dialogs? I see several options:
1. use stderr and implement a `--quiet` flag to suppress warnings and errors (or replace `--verbosity` with `--loglevel <LEVEL>` with LEVEL being the lowest level that gets printed)
2. use stdout, then `--quiet` isn't necessary as users can just pipe stderr to `/dev/null` (although in my personal opinion a CLI argument to control this makes for a better user experience than having to pipe stuff to `/dev/null `)

I strongly prefer 1. here, as using stdout for questions makes it impossible to pipe stdout to a file, so it would be either deciding to use `--yes` or `--no` to avoid dialogs altogether or not being able to pipe to stdout without risking to not see the question because the question text was piped to a file instead of the terminal 

---

# `tracing`
As far as I understand, `log` is somewhat being replaced by the more powerful and flexible `tracing`. I haven't worked with that, but I'm fairly certain that what I described above is equally possible with tracing (printing to stderr and optionally to a file)

If you'd be interested, I would be happy to look into `tracing` and how to use it / which subscriber (the logger equivalent) crate looks simple and flexible enough.

---

_(sorry for the long text on an already closed issue, I just think settling for a proper logging solution now could spare us much hassle later on)_

**Comment by marcospb19** [comment]
I don't have opinions against using `log` here, you can create a new issue, from the comment above, to see if anyone wants to make a PR to solve it, I would merge it :) .

I like the advantages, I won't be implementing it myself just because I need to do other stuff, code quality is lacking, to be honest, and that's my fault xD.

**Comment by AntonHermann** [comment]
Great. I try to work on it if I can spare some time, but I'm pretty busy myself at the moment, couldn't afford to program nearly as much as I'd like to sadly :(
