### ISSUE TITLE
Accept flags in any position

### ISSUE THREAD

**Issue by marcospb19** [ouch-org/ouch#233]
Currently, if we type:
```shell
ouch decompress archive.zip --yes
```

`ouch` will complain that this flag does not exist, instead, you should write it like this:

```shell
ouch --yes decompress archive.zip
```

Would be nicer if the the flags `--yes`, `--no`, and `--accessible`, plus the incoming `--store-symlinks`, `--gitignore` and `--format`, could be added in any place.

**Comment by marcospb19** [comment]
@figsoda @SpyrosRoum can this be tweaked in our current usage of `clap`? Or would I need to do this check before calling `clap` functions?

**Comment by SpyrosRoum** [comment]
The issue here is that `--yes`/`--no` are options for the `ouch` commands and not the `compress`/`decompress` sub-commands.
I don't know the best solution to this but one of them (I think) is to make them options of the sub-commands instead of the main command.

`clap` authors/users might have a better solution, I haven't had to do this before
