### ISSUE TITLE
ouch for "standard" linux

### ISSUE THREAD

**Issue by black-snow** [ouch-org/ouch#266]
Maybe I'm blind but I can't find a version for a "standard" linux - read Ubuntu / Debian / Mint / what have you. The brew formula is for macOS only, no repo for default package managers, the release files state musl. Is this something that's still on the roadmap?

**Comment by marcospb19** [comment]
Hey, thanks for asking.

You can try the `musl` version, it's currently our "standard" linux binary that does not require any dependencies.

In future releases we might have a `gnu` alternative too, however, that would require more explanation on installation instructions for each system, I do prefer the `musl` one because it's easier to set up.

**Comment by black-snow** [comment]
@marcospb19 thanks for the quick reply. I'll give it a shot. If the musl one runs well on GNU/Linux then we should be able to fix [this](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/ouch.rb#L18), shouldn't we?

**Comment by marcospb19** [comment]
Maybe the person who packaged it didn't had a Linux system to test it on, idk.

The script you showed me uses `cargo install` and compiles from source instead of installing a pre-built binary.

THe build-from-source approach does not benefir from us providing a `musl` binary, also, Linux by default uses a `linux-unknown-gnu` so it's not even trying to compile into `musl`.

I do usually prefer using packages that just install the binary instead, but packaging is not on my hands.

**Comment by black-snow** [comment]
Aight, thanks. Might look into this myself some time in the future. Gonna close this for now.
