### ISSUE TITLE
Drop Windows support 

### ISSUE THREAD

**Issue by marcospb19** [ouch-org/ouch#272]
Moving discussion from #271.

We are considering dropping support for non-`Unix` (`Windows` included) support because the majority of `Ouch`'s contributors do not own a Windows system to test and ensure the quality.

Also because the majority of the users use a `Unix` system anyways, in `Windows` people usually use `WinRar` or `7Zip`.

Plus, `Ouch` is already supported with `WSL`.

**Comment by hut8** [comment]
Hey there. I'm a Windows user (part-time). The way that I got to ouch, actually, was because Windows of course does not come with any CLI utility for gzip or other formats, and I didn't want to install some proprietary binary like 7z with an inconsistent CLI. WSL is not a good choice for what I'm doing. WSL1 has poor syscall compatibility and WSL2 has extremely poor filesystem performance between Windows and the guest VM. This tool is really a blessing for Windows users.

If you have individual issues that I could help with that are windows-specific, I will be glad to help. GitHub actions makes it really easy to test on MacOS, Windows, and Linux.

Just my two cents 😄

**Comment by marcospb19** [comment]
I'm a bit surprised Ouch actually has a Windows user, but yeah it does make sense.

I have changed my mind, I think we can keep Windows support, however we might want communicate better to the users that this support isn't the best as our tests are currently lacking and our contributors (at the time of this writing) do not use Windows.

I don't want to market Ouch as "cross-platform" and lead people to disappointment.

**Comment by hut8** [comment]
That sounds like a great plan. Let me know if you want help with specific issues. I'm kind of a beginner at Rust and am mostly interested in this project as a user, but certainly would love to help wherever I can.

**Comment by rasa** [comment]
ouch can be installed via [scoop](https://scoop.sh/) now:
`scoop install ouch`
Can this issue be closed now?

**Comment by figsoda** [comment]
I think we can close this now, just to not scare new Windows users off. Even though windows support is not actively tested, it should be working mostly fine, and I don't think we will be dropping Windows support any time soon.
