### ISSUE TITLE
[Feature request] Smart assumption of the user intention

### ISSUE THREAD

**Issue by freijon** [ouch-org/ouch#425]
I think it's a bit tedious that we're forced to either "compress" or "decompress". And while it's easy enough with the aliases "c" and "d", I think `ouch` could be a bit smarter in detecting what the user probably wants. I think that would be a big UX improvement. One of the pain points (for me) of other archive tools is that I have to remember all their flags to compress/decompress like `xf` for tar.

- If I execute `ouch file.zip` I think it's safe to assume that I want `file.zip` decompressed with default options.
- If I execute `ouch <non-archive> <archive>` it would be safe to assume that I intend to compress `<non-archive>` in `<archive>`.

To be clear, I'm not asking to remove the subommands, just to make smart assumptions by default and leave these subcommands for special cases where we need to further specify our intention.

**Comment by marcospb19** [comment]
Beware of the long response!

By far this is not a bad suggestion, unfortunately, it's hard to implement, not because it would take long, but because we're already very low on contributor power to fix existing issues and add new formats, and if we add this, we'd be receiving more issues complaining about corner cases I didn't cover, or trying to improve it a step further.

---

You're assuming a case where we have two options:

1. `ouch <non-archive...> <archive>` (compression)
2. `ouch <archive...>` (decompression)

But take this example:

```sh
ouch rar.rar zip.zip
```

You'd expect `ouch` to decompress both archives, but compression would happen instead because right now `ouch` doesn't support `.rar` archives, and extension detection only happens for supported formats.

And what if I want to put an archive inside another one?

```sh
ouch rar.rar zip.zip
```

Same usage but two possible intentions.

---

```sh
ouch gz.gz zip.zip
```

Behavior here isn't clear, should it decompress both files or add a Gzipped file inside a new Zip archive?

Another one:

```sh
ouch tar.tar archive.tar.gz
```

Both are archives, one is gzipped, I want to transform `.tar` -> `.tar.gz`.

---

It's not clear what `ouch` should do in every case, even if we come to an agreement on the _most intuitive behavior_, we can't guarantee that people will make the same assumptions as us. 

And making it more confusing is contrary to the objective of being "obvious" and easy to learn/teach.

By sticking to _subcommands_ we also ensure that the user gets a good and predictable error message.

I can think of a couple more counter-intuitive dilemmas, but this comment is already very long xD.

---

I believe what you want can be easily solved with aliases inside your `~/.bashrc` or `~/.zshrc`:

```sh
alias decompress="ouch decompress"
alias compress="ouch compress"
```

or even

```sh
alias decomp="ouch decompress"
alias comp="ouch compress"
```

I could even add an `alias` suggestion to our README.md.

---

Closing for now, but feel free to add more.
