### ISSUE TITLE
About 0.4.2 release

### ISSUE THREAD

**Issue by chenrui333** [ouch-org/ouch#482]
👋 it looks like 0.4.2 release was not completed, ie the release notes was not created. Raise this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/138967

**Comment by figsoda** [comment]
Hi! I have a draft release ready that is visible to org members, but I wasn't able to contact @marcospb19, who merged my [version bump pull request](https://github.com/ouch-org/ouch/pull/477): https://github.com/ouch-org/ouch/pull/481#issuecomment-1670490971. @vrmiguel, since you seems to be more active at this moment, would you mind double-checking my draft release notes and consider undrafting it for the official release? Thanks!

**Comment by marcospb19** [comment]
@figsoda I installed a Matrix client in my smartphone, now I have notifications so I'll never lose a ping again.

Sorry, it won't happen again :sweat_smile:.

The draft looked good so I released it https://github.com/ouch-org/ouch/releases/tag/0.4.2 :tada: 

Thanks folks
