### ISSUE TITLE
Use `fs-err` crate instead of `std::fs`

### ISSUE THREAD

**Issue by marcospb19** [ouch-org/ouch#56]
That will give more context to errors when dealing with filesystem operations.

To replace it:

```rust
// Replace this
use std::fs;

// By this
use fs_err as fs;
```

**Comment by marcospb19** [comment]
We should however use it carefully, as it changes how our error messages are displayed, the new messages can become redundant and ugly.

So we shall test some errors after this change to see how common errors change.

**Comment by marcospb19** [comment]
Also, are we going to use `AnyHow` to add context?

For example, sometimes the problem can halt with the message "file not found".

Which file? When?

With this issue resolved, instead, we'll have "File PATH_TO_FILE not found, while trying to read from".

Still, it could contain more context, why were we trying to read from it? Is it for decompressing? Loading configurations?

**Comment by GabrielSimonetto** [comment]
We have a problem, external libraries not necessarily will accept our fs type:

Here I have changed fs on src/archive/tar.rs

```
use std::{
    env,
    // fs,
    io::prelude::*,
    path::{Path, PathBuf},
};

use fs_err as fs;
...
```

```
error[E0308]: mismatched types
  --> src/archive/tar.rs:62:43
   |
62 |                 builder.append_file(path, &mut file)?;
   |                                           ^^^^^^^^^ expected struct `std::fs::File`, found struct `fs_err::File`
   |
   = note: expected mutable reference `&mut std::fs::File`
              found mutable reference `&mut fs_err::File`

For more information about this error, try `rustc --explain E0308`.
```

Which makes sense. Our external dependency tar tries to use specifically the std fs:

`    pub fn append_file<P: AsRef<Path>>(&mut self, path: P, file: &mut fs::File) -> io::Result<()> {...}`

The same thing doesn't seem to be a problem with serde_json, because they are using generic types? idk that seems to be the case:

```
#[cfg(feature = "std")]
#[cfg_attr(docsrs, doc(cfg(feature = "std")))]
pub fn from_reader<R, T>(rdr: R) -> Result<T>
where
    R: crate::io::Read,
    T: de::DeserializeOwned,
{
    from_trait(read::IoRead::new(rdr))
}
```

So, we have a few options/questions:
1- Is it possible to solve this on our end?
2- If it's not, should we vendor the tar lib? (probably not)
3- We could make a PR to them (the external tar lib) implementing generic stuff, but that will take some time.
4- If we aren't doing any of these, should we just not use fs_err when interacting with external libraries that have an issue with it?

A last point, do you guys think this is a valid issue to create on the fs_err github? Just asking how to deal with these kinds of issues? Because it seems to me there is nothing to be made, but maybe smarter people have other ideas to solve this on our end without involving the tar lib.

**Comment by GabrielSimonetto** [comment]
It has been brought to my attention that there are wrappers on fs-err that deal with this :pineapple: 

https://docs.rs/fs-err/2.6.0/fs_err/struct.File.html#method.file_mut

Sadly we won't be able to enjoy the better error messages inside such operations, so maybe my decision points are still somewhat relevant (but not a barrier anymore)

**Comment by GabrielSimonetto** [comment]
Hey (: I'll follow up on your suggestions later when I can test them out, thanks for the input!

As for the `zip` it seems to be fine, the only problem we had is easily fixable by importing permissions directly from `fs`

```
error[E0433]: failed to resolve: could not find `Permissions` in `fs`
   --> src/archive/zip.rs:130:44
    |
130 |         fs::set_permissions(file_path, fs::Permissions::from_mode(mode))?;
    |                                            ^^^^^^^^^^^ not found in `fs`
    |
help: consider importing this struct
    |
3   | use std::fs::Permissions;
    |
```
